#!/bin/bash

# Defaults
BUILD=false

while getopts ":b" opt; do
    case $opt in
        b) # Build
            BUILD=true
            ;;
    esac
done

# Stop all running containers
docker-compose --file ./docker-compose.yml stop

# Clean up and start containers
if [ "$BUILD" == true ]
then
    docker-compose --file ./docker-compose.yml up --force-recreate
else
    docker-compose --file ./docker-compose.yml up
fi

# docker run -v $(PWD)/src:/var/www -w /var/www node:12.16 npm install -g live-server
# docker run -v $(PWD)/src:/var/www -w /var/www node:12.16 npm install --no-optional
